### ISSUE TITLE
[4.6.1] Bug: <describe issue>

### ISSUE THREAD

**Issue by Nalharby** [hirosystems/stacks-wallet#1089]
Hello

I formatted my laptop and was able to retrieve my Hiro wallet as well as my ELECTRUM wallet which should contain my mined BTC from STX stacking.

The problem is my mined BTC is not showing on my EECTRUM wallet although I've tried every possible way to no avail

**Comment by 314159265359879** [comment]
@Nalharby have you retrieved your Stacking rewards? Sorry for the late response, I believe this may have been missed because of the missing title. 

How did you stack exactly, did you do so in a pool or on your own? If you stacked on your own, did you check the rewards in the historic records using the BTC address you used? stacking.club

If you stacked in a pool that paid out in BTC such as planbetter.org you can check the BTC rewards by using the instructions on their website: https://planbetter.org/payouts
