### ISSUE TITLE
[4.5.3] Bug: <describe issue> I can't withdraw MIA tokens from wallet.  Will this ever be fixed?

### ISSUE THREAD

**Issue by tek1022** [hirosystems/stacks-wallet#973]
Bug found testing Hiro Wallet build undefined, 4.5.3.

**Comment by markmhx** [comment]
We don't have an estimate yet for when #897 would be available since the work hasn't been prioritized yet. However, we've already begun work on supporting Ledger in the extension version of the wallet with https://github.com/hirosystems/stacks-wallet-web/issues/951 and hope to release it later this year or early next.

**Comment by edwolf** [comment]
My MIA coins are also now stuck on Hiro Desktop Wallet with Ledger enabled. When will Ledger be enabled on the web extension?

**Comment by kyranjamie** [comment]
We are working on Ledger support for web wallet currently. We aim to release in Q1 2022.
